baseURL = "https://nmcapule.dev"
languageCode = "en-us"
theme = "terminal"
paginate = 5
googleAnalytics = "UA-166912390-1"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "nmcapule.dev"
    subtitle = "-. .- - .... .- -. .. . .-.."
    owner = "Nathaniel Capule"
    keywords = "programming stuff"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "nmcapule.dev"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/nmcapule"
      [[languages.en.menu.main]]
        identifier = "linkedin"
        name = "Linkedin"
        url = "https://ph.linkedin.com/in/nathaniel-capule-908a8965"
      [[languages.en.menu.main]]
        identifier = "search"
        name = "x CodeSearch"
        url = "https://cs.nmcapule.dev"
      [[languages.en.menu.main]]
        identifier = "code"
        name = "x Cider"
        url = "https://code.nmcapule.dev"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
